spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: false
            temp:
            use_jdbc_metadata_defaults: false
    datasource:
#        url: jdbc:postgresql://test-pets-db-postgres/test-pets-db
        url: jdbc:postgresql://localhost:5432/test-pets-db
        username: postgres
        password: 123

#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#spring.http.log-request-details: true
